lag-generator:
  maxLagInMilliseconds: 10000
  lagIncrement: 10

resilience4j.circuitbreaker:
  instances:
    productDb:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 1
      waitDurationInOpenState: 60s
      failureRateThreshold: 50

spring:

  datasource:
    url: jdbc:postgresql://dmserver/l9sql
    initialization-mode: never
    username: l9sql_user
    password: l9su1234

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
