spring:

  shell:
    interactive:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: never

  jpa:
    hibernate:
      naming:
        physical-strategy: ru.otus.demen.books.dao.CustomPhysicalNamingStrategy
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  h2:
    console:
      enabled: true
      path: /h2-console