spring:

  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: never

  jpa:
    hibernate:
      naming:
        physical-strategy: ru.otus.demen.books.dao.CustomPhysicalNamingStrategy
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,loggers,metrics
