actuator:

  health:
    books:
      host-for-check: localhost
      path-for-check: /api/books

logging:
  file:
    name: home_work.log

management:

  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: health,logfile,metrics


server:
  port: 8080


spring:

  data:
    rest:
      base-path: /datarest

  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: never

  jpa:
    hibernate:
      naming:
        physical-strategy: ru.otus.demen.books.dao.CustomPhysicalNamingStrategy
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
